services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: ghcr.io/unevenmike/vibe-pad:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`michaelbutterfield.dev`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
    container_name: vibe-pad
    environment:
      - DB_PATH=/data/notes.db
    volumes:
      - ./data:/data
