services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: ghcr.io/unevenmike/vibe-pad:latest
    container_name: vibe-pad
    environment:
      - DB_PATH=/data/notes.db
    volumes:
      - ./data:/data
