services:
  app:
    image: ghcr.io/unevenmike/vibe-pad:latest
    container_name: vibe-pad
    environment:
      - DB_PATH=/data/notes.db
    volumes:
      - ./data:/data
    ports:
      - "3000:3000" # ✅ Expose port 3000 to the host
